version: "3"
services:
  db:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -p 5432" ]
      interval: 10s
      timeout: 3s
      retries: 3
    environment:
      PGUSER: postgres
      POSTGRES_USER: postgres
      POSTGRESQL_PASSWORD: admin
      POSTGRES_DB: microsensors
    restart: on-failure

  sensors-dashboard:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: mvc-app.Dockerfile
    image: "microsensors:0.0.1-SNAPSHOT"
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/microsensors
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 60
        window: 30s
