server:
  port: 8080
  error:
    include-message: always
    include-exception: true

springfox:
  documentation:
    enabled: false
spring:
  application:
    name: sensor
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${REMOTE_DATABASE_URL:jdbc:postgresql://localhost:5432/microsensors}
    username: ${REMOTE_DATABASE_USERNAME:postgres}
    password: ${REMOTE_DATABASE_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: 'true'
      hibernate:
        ddl-auto: update
      show-sql: 'true'
    hikari:
      maximum-pool-size: 50

  main:
    allow-bean-definition-overriding: true
    lazy-initialization: false
  flyway:
    enabled: true
#    baseline-on-migrate: true
    validate-on-migrate: true
  mvc:
    format:
      date: yyyy.MM.dd
      date-time: yyyy.MM.dd HH:mm
      time: HH:mm:ss
    view:
      prefix: /
      suffix: .jsp
    pathmatch:
      matching-strategy: ant_path_matcher