server:
  error:
    include-message: always
    include-exception: true
  ssl:
    key-store: ${SERVER_SSL_KEY-STORE:open-sensor-data.systems.p12}
    key-alias: ${SERVER_SSL_KEY-ALIAS:open-sensor-data.systems}
    enabled-protocols: TLSv1.1,TLSv1.2,TLSv1.3
    key-password: ${SERVER_SSL_KEY-PASSWORD}
    trust-store-password: ${SERVER_SSL_KEY-STORE-PASSWORD}
    key-store-type: ${SERVER_SSL_KEY-STORE-TYPE:pkcs12}
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
  port: 443
springfox:
  documentation:
    enabled: false
spring:
  application:
    name: sensor
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${REMOTE_DATABASE_URL:jdbc:postgresql://localhost:5432/microsensors}
    username: ${REMOTE_DATABASE_USERNAME:postgres}
    password: ${REMOTE_DATABASE_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: 'true'
      hibernate:
        ddl-auto: update
      show-sql: 'true'
    hikari:
      maximum-pool-size: 50

  main:
    allow-bean-definition-overriding: true
    lazy-initialization: false
  flyway:
    enabled: true
    #    baseline-on-migrate: true
    validate-on-migrate: true
  mvc:
    format:
      date: yyyy.MM.dd
      date-time: yyyy.MM.dd HH:mm
      time: HH:mm:ss
    view:
      prefix: /
      suffix: .jsp
    pathmatch:
      matching-strategy: ant_path_matcher