INSERT INTO sensor_types (name)
VALUES ('Humidity sensor'),
       ('Geophone'),
       ('Hydrophone'),
       ('Microphone'),
       ('Pickup'),
       ('Seismometer'),
       ('Sound locator'),
       ('Push broom scanner'),
       ('AFR sensor'),
       ('Air–fuel ratio meter'),
       ('Blind spot monitor'),
       ('Crankshaft position sensor'),
       ('Curb feeler'),
       ('Defect detector'),
       ('Engine coolant temperature sensor'),
       ('Hall effect sensor'),
       ('Wheel speed sensor'),
       ('Airbag sensors'),
       ('Automatic transmission speed sensor'),
       ('Brake fluid pressure sensor'),
       ('Camshaft position sensor'),
       ('Cylinder Head Temperature gauge'),
       ('Engine crankcase pressure sensor'),
       ('Exhaust gas temperature sensor'),
       ('Fuel level sensor'),
       ('Fuel pressure sensor'),
       ('Knock sensor'),
       ('Light sensor'),
       ('MAP sensor'),
       ('Mass airflow sensor'),
       ('Oil level sensor'),
       ('Oil pressure sensor'),
       ('Omniview technology'),
       ('Oxygen sensor'),
       ('Parking sensor'),
       ('Radar gun'),
       ('Radar sensor'),
       ('Speed sensor'),
       ('Throttle position sensor'),
       ('Tire pressure sensor'),
       ('Torque sensor'),
       ('Transmission fluid temperature sensor'),
       ('Turbine speed sensor'),
       ('Variable reluctance sensor'),
       ('Vehicle speed sensor'),
       ('Water-in-fuel sensor'),
       ('Unattended Ground sensor'),
       ('ABS sensors'),
       ('Breathalyzer'),
       ('Carbon dioxide sensor'),
       ('Carbon monoxide detector'),
       ('Catalytic bead sensor'),
       ('Chemical field-effect transistor'),
       ('Chemiresistor'),
       ('Electrochemical gas sensor'),
       ('Electronic nose'),
       ('Electrolyte–insulator–semiconductor sensor'),
       ('Energy-dispersive X-ray spectroscopy'),
       ('Fluorescent chloride sensors'),
       ('Holographic sensor'),
       ('Hydrocarbon dew point analyzer'),
       ('Hydrogen sensor'),
       ('Hydrogen sulfide sensor'),
       ('Infrared point sensor'),
       ('Ion-selective electrode'),
       ('ISFET'),
       ('Nondispersive infrared sensor'),
       ('Microwave chemistry sensor'),
       ('Morphix Chameleon'),
       ('Nitrogen oxide sensor'),
       ('Thin-film thickness monitor'),
       ('Olfactometer'),
       ('Optode'),
       ('Sun sensor'),
       ('Ozone monitor'),
       ('Pellistor'),
       ('pH glass electrode'),
       ('Potentiometric sensor'),
       ('Redox electrode'),
       ('Smoke detector'),
       ('Zinc oxide nanorod sensor'),
       ('Current sensor'),
       ('Daly detector'),
       ('Electroscope'),
       ('Electron multiplier'),
       ('Faraday cup'),
       ('Galvanometer'),
       ('Structured-light 3D scanner'),
       ('Hall probe'),
       ('Magnetic anomaly detector'),
       ('Magnetometer'),
       ('Magnetoresistance'),
       ('MEMS magnetic field sensor'),
       ('Metal detector'),
       ('Planar Hall sensor'),
       ('Radio direction finder'),
       ('Test light'),
       ('Voltage detector'),
       ('Actinometer'),
       ('Air pollution sensor'),
       ('Bedwetting alarm'),
       ('Ceilometer'),
       ('Dew warning'),
       ('SSMIS'),
       ('Fish counter'),
       ('Frequency domain sensor'),
       ('Gas detector'),
       ('Hook gauge evaporimeter'),
       ('Humistor'),
       ('Hygrometer'),
       ('Leaf sensor'),
       ('Lysimeter'),
       ('Pyranometer'),
       ('Pyrgeometer'),
       ('Psychrometer'),
       ('Rain gauge'),
       ('Rain sensor'),
       ('SSIES'),
       ('SNOTEL'),
       ('Snow gauge'),
       ('Soil moisture sensor'),
       ('Stream gauge'),
       ('Tide gauge'),
       ('Weather radar'),
       ('Air flow meter'),
       ('Anemometer'),
       ('Flow sensor'),
       ('Gas meter'),
       ('Mass flow sensor'),
       ('Water meter'),
       ('Bubble chamber'),
       ('Cloud chamber'),
       ('Geiger counter'),
       ('Geiger–Müller tube'),
       ('Ionization chamber'),
       ('Gaseous ionization detectors'),
       ('Neutron detection'),
       ('Particle detector'),
       ('Proportional counter'),
       ('Scintillator'),
       ('Scintillation counter'),
       ('Semiconductor detector'),
       ('Thermoluminescent dosimeter'),
       ('Wire chamber'),
       ('Airspeed indicator'),
       ('Altimeter'),
       ('Attitude indicator'),
       ('Depth gauge'),
       ('Fluxgate compass'),
       ('Gyroscope'),
       ('Inertial navigation system'),
       ('Inertial reference unit'),
       ('Machmeter'),
       ('Magnetic compass'),
       ('MHD sensor'),
       ('Ring laser gyroscope'),
       ('Sextant'),
       ('Turn coordinator'),
       ('Variometer'),
       ('Vibrating structure gyroscope'),
       ('Yaw-rate sensor'),
       ('Accelerometer'),
       ('Auxanometer'),
       ('Capacitive displacement sensor'),
       ('Capacitive sensing'),
       ('Flex sensor'),
       ('Free fall sensor'),
       ('Gravimeter'),
       ('Gyroscopic sensor'),
       ('Impact sensor'),
       ('Inclinometer'),
       ('Incremental encoder'),
       ('Integrated circuit piezoelectric sensor'),
       ('Laser rangefinder'),
       ('Laser surface velocimeter'),
       ('LIDAR'),
       ('Linear encoder'),
       ('Linear variable differential transformer (LVDT)'),
       ('Liquid capacitive inclinometers'),
       ('Odometer'),
       ('Photoelectric sensor'),
       ('Piezoelectric accelerometer'),
       ('Position sensor'),
       ('Position sensitive device'),
       ('Angular rate sensor'),
       ('Rotary encoder'),
       ('Rotary variable differential transformer'),
       ('Selsyn'),
       ('Shock detector'),
       ('Shock data logger'),
       ('Sudden Motion Sensor'),
       ('Tilt sensor'),
       ('Tachometer'),
       ('Ultrasonic thickness gauge'),
       ('Ultra-wideband radar'),
       ('Positron emission tomography'),
       ('Velocity receiver'),
       ('Magnetic sensor'),
       ('Charge-coupled device'),
       ('CMOS sensor'),
       ('Angle–sensitive pixel'),
       ('Colorimeter'),
       ('Contact image sensor'),
       ('Electro-optical sensor'),
       ('Flame detector'),
       ('Infra-red sensor'),
       ('Kinetic inductance detector'),
       ('LED as light sensor'),
       ('Light-addressable potentiometric sensor'),
       ('Nichols radiometer'),
       ('Fiber optic sensors'),
       ('Optical position sensor'),
       ('Thermopile laser sensors'),
       ('Photodetector'),
       ('Photodiode'),
       ('Photomultiplier'),
       ('Photomultiplier tube'),
       ('Phototransistor'),
       ('Polygraph'),
       ('Photoionization detector'),
       ('Optical coherence tomography'),
       ('Photoresistor'),
       ('Photoswitch'),
       ('Phototube'),
       ('Scintillometer'),
       ('Shack–Hartmann wavefront sensor'),
       ('Single-photon avalanche diode'),
       ('Superconducting nanowire single-photon detector'),
       ('Transition-edge sensor'),
       ('Visible Light Photon counter'),
       ('Wavefront sensor'),
       ('Barograph'),
       ('Barometer'),
       ('Boost gauge'),
       ('Bourdon gauge'),
       ('Hot filament ionization gauge'),
       ('Ionization gauge'),
       ('McLeod gauge'),
       ('Oscillating U-tube'),
       ('Permanent downhole gauge'),
       ('Piezometer'),
       ('Pirani gauge'),
       ('Pressure sensor'),
       ('Pressure gauge'),
       ('Tactile sensor'),
       ('Time pressure gauge'),
       ('Bhangmeter'),
       ('Hydrometer'),
       ('Force gauge'),
       ('Level sensor'),
       ('Force sensor'),
       ('Load cell'),
       ('Magnetic level gauge'),
       ('Nuclear density gauge'),
       ('Piezocapacitive pressure sensor'),
       ('Piezoelectric sensor'),
       ('Strain gauge'),
       ('Organoleptic sensor'),
       ('Viscometer'),
       ('Bolometer'),
       ('Bimetallic strip'),
       ('Calorimeter'),
       ('Exhaust gas temperature gauge'),
       ('Gardon gauge'),
       ('Golay cell'),
       ('Heat flux sensor'),
       ('Infrared thermometer'),
       ('Microbolometer'),
       ('Microwave radiometer'),
       ('Net radiometer'),
       ('Quartz thermometer'),
       ('Resistance thermometer'),
       ('Silicon bandgap temperature sensor'),
       ('Special sensor microwave/imager'),
       ('Temperature gauge'),
       ('Thermistor'),
       ('Thermocouple'),
       ('Thermometer'),
       ('Phosphor thermometry'),
       ('Pyrometer'),
       ('Alarm sensor'),
       ('Doppler radar'),
       ('Motion detector'),
       ('Occupancy sensor'),
       ('Proximity sensor'),
       ('Passive infrared sensor'),
       ('Reed switch'),
       ('Stud finder'),
       ('Triangulation sensor'),
       ('Touch switch'),
       ('Wired glove'),
       ('Active pixel sensor'),
       ('Back-illuminated sensor'),
       ('BioFET'),
       ('Biochip'),
       ('Biosensor'),
       ('Capacitance probe'),
       ('Nano-tetherball sensor'),
       ('Catadioptric sensor'),
       ('Carbon paste electrode'),
       ('Digital sensors'),
       ('Displacement receiver'),
       ('Electromechanical film'),
       ('Nanosensor'),
       ('Electrochemical fatigue crack sensor'),
       ('Fabry–Pérot interferometer'),
       ('Fiber Bragg grating'),
       ('Fisheries acoustics'),
       ('Image sensor'),
       ('Inductive sensor'),
       ('Intelligent sensor'),
       ('Lab-on-a-chip'),
       ('Molecular sensor'),
       ('Quantum sensor'),
       ('Radar'),
       ('Ground-penetrating radar'),
       ('Synthetic aperture radar'),
       ('Radar tracker'),
       ('Stretch sensor'),
       ('Sonar'),
       ('Tapered element oscillating microbalance'),
       ('Transducer'),
       ('Video sensor'),
       ('Wheatstone bridge'),
       ('TriDAR'),
       ('Speedometer'),
       ('Pitometer logs'),
       ('Pitot tubes'),
       ('Airspeed indicators'),
       ('Piezo sensors'),
       ('Moire deflectometry'),
       ('Ground speed radar'),
       ('Millimeter wave scanner'),
       ('ANPR'),
       ('Laser surface velocimeters'),
       ('Actigraphy'),
       ('Littoral Airborne Sensor/Hyperspectral'),
       ('Atomic Gravitational Wave Interferometric Sensor'),
       ('LORROS'),
       ('Chemoreceptor'),
       ('Cryogenic particle detector'),
       ('Laser beam profiler'),
       ('Electronic tongue'),
       ('Fine Guidance sensor'),
       ('Flat panel detector'),
       ('Glass break detector'),
       ('Heartbeat sensor'),
       ('Hyperspectral sensor'),
       ('IRIS (Biosensor)');
